export const dataLisst = [
  {
    categories: 'newDish',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'newDish',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'newDish',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'newDish',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'newDish',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'BakedNoodles',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'BakedNoodles',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'BakedNoodles',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'BakedNoodles',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'BakedNoodles',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'piza',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'piza',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'piza',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'piza',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'piza',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'Appetizer',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Appetizer',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Appetizer',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Appetizer',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Appetizer',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'Spaghetti',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Spaghetti',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Spaghetti',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Spaghetti',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Spaghetti',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'Salad',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Salad',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Salad',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Salad',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Salad',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'drink',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'drink',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'drink',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'drink',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'drink',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'Seafood',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-17.png',
    name: 'Pizza Golden 4 Cheese',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Seafood',
    id: 2,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/best-chatbot-templates-insurance-chatbots-finance-2.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Seafood',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-24.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Seafood',
    id: 4,
    image: 'hhttps://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Seafood',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/derwent-park-pizza-5.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'mixed',
    id: 1,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-33.png',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'mixed',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-8.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'mixed',
    id: 3,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/pepperoni-pizza-image-cuginos-pizzeria-35.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'mixed',
    id: 4,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/pizza-prevents-cancer-find-what-more-does-20.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'mixed',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-clip-image-download-1.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'Stuffing',
    id: 1,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/pizza-slice-duvet-cover-sale-diane-diederich-22.png',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Stuffing',
    id: 2,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-0.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Stuffing',
    id: 3,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-19.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Stuffing',
    id: 4,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-images-download-pizza-19.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Stuffing',
    id: 5,
    image: 'https://www.freepnglogos.com/uploads/pizza-png/pizza-transparent-image-pictures-25.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },

  {
    categories: 'Traditional',
    id: 1,
    name: 'Pizza  4 Cheese Pizza ',
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/download-pepperoni-pizza-transparent-image-15.png',
    price: 309000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Traditional',
    id: 2,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/download-pepperoni-pizza-transparent-image-15.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Traditional',
    id: 3,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/download-pepperoni-pizza-transparent-image-15.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Traditional',
    id: 4,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/download-pepperoni-pizza-transparent-image-15.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
  {
    categories: 'Traditional',
    id: 5,
    image:
      'https://www.freepnglogos.com/uploads/pizza-png/download-pepperoni-pizza-transparent-image-15.png',
    name: 'Pizza  4 Cheese',
    price: 129000,
    detail: 'Phủ phô mai Gouda thơm vàng',
  },
];
